@extends('layouts.app')
@section('title', $title)
@section('content')
    @include('site.sliders.banner_main')
    @include('site.tabs.tabs_box')
    @include('site.static_templates.subscription.subscription')
    @include('site.static_templates.download_mobile_apps')
    @include('site.sliders.advertisings')
    @include('site.static_templates.about')
@endsection
