@foreach($book_pages as $k=>$page)
    <div id="page-{{$page->page}}" data-page-number="{{$page->page}}" data-book-id="{{$page->book->id}}" class="page @if(in_array($page->page,$bookmarks)) marked @endif" @if(in_array($page->page,$bookmarks)) style="position: relative" @endif>
        @if(in_array($page->page,$bookmarks)) <img style="position: absolute;right: 2px;top: 2px;" width="14" height="18" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAASCAYAAABrXO8xAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAOVJREFUOI3tkz9KA3EQRt/MT8VgFTb+KVYv4AHMFazFVqxSiXgEj2DEyspeLLxE2FVbL2ACIqidGGJmxiYRExQ2rfjq7/ENw4wMb+vb4noO5FSjF+otsTLrziCN6c6NpbT1IlUMK7MA1nXGpi/+xT8uRievRSevVRbjZnnNysaxp/6Dp/dHK7J23NU3pnMyuj3UaXqKI0J2gPmp3AcSV2py4koxIX5jIMi1qLWx1Hf1FiF7wOKPjcATcKERZ9J87U2MX6ysutg+cMDom2RYZCUqp2np+VI2Gfy2DIC4Z8HeGrt4HH4CmWBVnyRr+ycAAAAASUVORK5CYII=" alt="active-book-mark"> @endif
            @php
                $content = str_replace(['<body>', '</body>'],'', '<body><div id="page-div" style="position:relative"><p style="margin:0;left:60px;" class="ft01">ӘОЖ 821.512.122КБЖ 84 Қаз 7-44Ә 13 </p><p style="margin:0;left:102px;text-align: center" class="ft01">Әбдәкімұлы Момбек</p><p style="margin:0;left:60px;" class="ft01">Ә 13  Қараман  қарақшы:  Хикаят..  –  Алматы:  «Дария  Дамыту </p><p style="margin:0;left:102px;text-align: center" class="ft01">Орталығы», 2020. – 380 б. </p><p style="margin:0;left:81px;" class="ft01">ISBN 9965-752-79-6</p><p style="margin:0;left:81px;" class="ft01">Қараманды халық шартты түрде «қарақшы» деп атағанымен, оның атқарған істері тасадан оқ атып, ауыл тентегінен ұзай алмайтын кейбір бұзықтардың қылықтарына мүлдем ұқсамайтын, тек қанішерлер мен баскесерлер ортасында әділдік орнатам деп күреске түскен, іс-әрекеті кең ауқымды қамтыған қаһарман болған.</p><p style="margin:0;left:81px;" class="ft01">Жамандыққа жаны қас Қараман, өмір бойы тек кедей мен шаруаға, кембағал мен жетім-жесірге зәбір көрсетушілермен күрескен. Ташкенттегі адам жегіш жөйіттермен  алысып,  оларды  қиратып  тастаған.  Кеңес  өкіметі  орнаған кезде  бейбіт  елді  басынып,  зәре-иманын  ұшырған  Өзбекстан,  Тәжікстан тауларындағы  қаскөй  басмашылармен  алысады.  Байлар  мен  саудагерлердің дүние-мүліктерін тартып алып, кедей-кепшікке таратып береді. Бірақ өзінің кейбір кереғар істері мен жеке көзқарасы үшін совет өкіметінің түрмелерінде бірнеше мәрте отыруына тура келеді.</p><p style="margin:0;left:81px;" class="ft01">Қараманның  он  бес  жасынан  қырық  бес  жасына  дейінгі  ғұмыры  «тас төсеніп,  күз  жастанып»  дегендей,  аласапыранмен  өткен.  Қолдарыңыздағы кітапта осылар туралы жан-жақты баяндалады. Мұны зердемен оқыған жан, оның өкімет тарапынан батыр деп мойындалмағанымен, күллі Қазақстан һәм Орта Азия халықтарының сүйікті қаһарманы әрі оларға өте жағымды тұлға болғанын  аңғарады.  Оның  қазақ  халқы  үшін  атқарған  істері  ағылшындық Робин Гудтың әрекеттерінен де асып түседі. Сондықтан да көпшілік ұғымында ол қайталанбас тұлға, сондай-ақ халық қаһарманы. Қалай десек те, Қараман күрделі  тұлға.  Оның  істері  жастарымыздың  ұлттық  жігерін  жандандыруға, әділетсіздіктің жолында аянбай күресуге үлгі болары хақ.</p><p style="margin:0;left:81px;" class="ft01">Қараманның үнемі биікті аңсайтын қыран жүрегі мен ылғи жеңісті мақсат тұтқан өр кеудесінің сыры осы кітапта жақсы ашылып, әдемі сипатталған.</p><p style="margin:0;left:432px;text-align: center" class="ft01">ӘОЖ 821.512.122</p><p style="margin:0;left:438px;text-align: center" class="ft01">КБЖ 84 Қаз 7-44</p><p style="margin:0;left:60px;" class="ft01"> ISBN 9965-752-79-6© «Дария Дамыту Орталығы», 2020© Момбек Әбдәкімұлы, 2020</p></div></body>');
                $content = preg_replace('/(left|top|right|bottom):[0-9]{1,}px;/', '', $content);
            @endphp
            {!! $content !!}
        <hr>
    </div>
@endforeach